apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /otusapp/gur-ok/?(.*)($|/)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.app.name }}
                port:
                  number: {{ .Values.service.app.port }}
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.app.name }}
                port:
                  number: {{ .Values.service.app.port }}