config:
  name: arch-brokerageaccount-configmap
  port: 8000
  ddl: validate
secret:
  name: arch-brokerageaccount-secret
deployment:
  app:
    image: gurok/arch_brokerageaccount
    port: 8000
    replicas: 2
  db:
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: arch-brokerageaccount-service
    type: ClusterIP
    protocol: TCP
    port: 9000
  db:
    name: postgresql-brokerageaccount-service
    host: "postgresql-brokerageaccount-service"
    type: ClusterIP
    port: 5432
    sport: "5432"
    dbname: arch_brokerageaccount_db
    dbschema: public
ingress:
  name: otus-brokerageaccount-ingress
  host: arch.homework