config:
  name: arch-stoplist-configmap
  port: 8000
  ddl: validate
secret:
  name: arch-stoplist-secret
deployment:
  app:
    image: gurok/arch_stoplist
    port: 8000
    replicas: 2
  db:
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: arch-stoplist-service
    type: ClusterIP
    protocol: TCP
    port: 9000
  db:
    name: postgresql-stoplist-service
    host: "postgresql-stoplist-service"
    type: ClusterIP
    port: 5432
    sport: "5432"
    dbname: arch_stoplist_db
    dbschema: public
ingress:
  name: otus-stoplist-ingress
  host: arch.homework