config:
  name: otus-hw03-configmap
  port: 8000
  ddl: validate
secret:
  name: otus-hw03-secret
deployment:
  app:
    type: NodePort
    image: gurok/arch_homework_2
    port: 8000
    replicas: 2
  db:
    type: NodePort
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: otus-hw03-service
    type: NodePort
    protocol: TCP
    port: 9000
  db:
    name: postgresql-service
    host: "postgresql-service"
    type: NodePort
    port: 5432
    sport: "5432"
    dbname: hw2db
    dbschema: public
ingress:
  name: otus-hw03-ingress
  host: arch.homework