apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}-service
  labels:
    app: {{ include "chart.name" . }}-app
    service: {{ include "chart.name" . }}-service
spec:
  selector:
    app: {{ include "chart.name" . }}-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" . }}-deployment-v1
  labels:
    app: {{ include "chart.name" . }}-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}-app
      version: v1
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}-app
        version: v1
    spec:
      containers:
        - name: health
          image: gurok/arch_homework_1
          ports:
            - name: web
              containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" . }}-deployment-v2
  labels:
    app: {{ include "chart.name" . }}-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}-app
      version: v2
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}-app
        version: v2
    spec:
      containers:
        - name: health
          image: gurok/arch_homework_1
          ports:
            - name: web
              containerPort: 8000
---