apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "chart.name" . }}-vs-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.name" . }}-vs
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "chart.name" . }}-vs-gateway
  http:
    - match:
        - uri:
            exact: /health
      route:
        - destination:
            host: {{ include "chart.name" . }}-service
            port:
              number: 9000
            subset: v1
          weight: 50
        - destination:
            host: {{ include "chart.name" . }}-service
            port:
              number: 9000
            subset: v2
          weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "chart.name" . }}-destination
spec:
  host: {{ include "chart.name" . }}-service
  subsets:
    - name: v1
      labels:
        version: "v1"
    - name: v2
      labels:
        version: "v2"
---