config:
  name: arch-profiles-configmap
  port: 8000
  ddl: create
secret:
  name: arch-profiles-secret
deployment:
  app:
    image: gurok/arch_profiles_3
    port: 8000
    replicas: 1
  db:
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: arch-profiles-service
    type: ClusterIP
    protocol: TCP
    port: 9000
  db:
    name: postgresql-profiles-service
    host: "postgresql-profiles-service"
    type: ClusterIP
    port: 5432
    sport: "5432"
    dbname: arch_profiles_db
    dbschema: public
